apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-api-deployment
  namespace: default
  labels:
    app: churn-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-api
  template:
    metadata:
      labels:
        app: churn-api
    spec:
      containers:
      - name: churn-api-container
        # !!! IMPORTANT: Replace this with your ECR image URI from the CI/CD pipeline
        image: [YOUR-AWS-ACCOUNT-ID].dkr.ecr.[YOUR-AWS-REGION][.amazonaws.com/churn-prediction-api:latest](https://.amazonaws.com/churn-prediction-api:latest)
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_PATH
          value: "/app/model.xgb"