apiVersion: v1
kind: Service
metadata:
  name: churn-api-service
  namespace: default
spec:
  selector:
    app: churn-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer